# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, pkgs-stable, modulesPath, ... }:
let
  systemSettings = {
    system = "x86_64-linux";
    timezone = "Europe/Rome";
    locale = "en_US.UTF-8";
    extraLocale = "it_IT.UTF-8";
  };

  specificSystemSettings = {
    hostname = "mainpc";
  };
in
{
  imports =
    [
      /etc/nixos/hardware-configuration.nix
      ../default.nix
    ];

  hardware.opentabletdriver.enable = true;

  pkgsOther.enable = true;
  gnome.enable = true;
  xdg.enable = true;
  mullvad.enable = true;
  samba.enable = true;
  ssh.enable = true;
  flatpak.enable = true;
  nvidia.enable = true;
  nixLd.enable = true;
  adb.enable = true;
  docker.enable = true;
  games.enable = true;
  virt.enable = true;

  programs.zsh.enable = true;

  services.xserver.videoDrivers = [ "nvidia" ];

  security.polkit.extraConfig = ''
    polkit.addRule(function(action, subject) {
      if (
        subject.isInGroup("users")
          && (
            action.id == "org.freedesktop.login1.reboot" ||
            action.id == "org.freedesktop.login1.reboot-multiple-sessions" ||
            action.id == "org.freedesktop.login1.power-off" ||
            action.id == "org.freedesktop.login1.power-off-multiple-sessions"
          )
        )
      {
        return polkit.Result.YES;
      }
    });
  '';

  networking.firewall = {
    enable = true;
  };

  # Bootloader.
  boot.loader = {
    systemd-boot.enable = true;
    efi = {
      canTouchEfiVariables = true;
      efiSysMountPoint = "/boot";
    };
  };

  # Networking
  networking.hostName = specificSystemSettings.hostname; # Define your hostname.
  networking.networkmanager.enable = true; # Use networkmanager

  # Timezone and locale
  time.timeZone = systemSettings.timezone; # time zone
  i18n.defaultLocale = systemSettings.locale;
  i18n.extraLocaleSettings = {
    LC_ADDRESS = systemSettings.extraLocale;
    LC_IDENTIFICATION = systemSettings.extraLocale;
    LC_MEASUREMENT = systemSettings.extraLocale;
    LC_MONETARY = systemSettings.extraLocale;
    LC_NAME = systemSettings.extraLocale;
    LC_NUMERIC = systemSettings.extraLocale;
    LC_PAPER = systemSettings.extraLocale;
    LC_TELEPHONE = systemSettings.extraLocale;
    LC_TIME = systemSettings.extraLocale;
  };
}
